name: Daily Arxiv
env:
  TZ: Asia/Shanghai
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Run script
        env:
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          ARXIV_QUERY: ${{ vars.ARXIV_QUERY }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          MAX_PAPER_NUM: ${{ vars.MAX_PAPER_NUM }}
          MODEL_NAME: ${{ vars.MODEL_NAME }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          
        run: |
          uv run main.py
          # Create archive directory if it doesn't exist
          mkdir -p archive
          
          # Get current and previous dates
          TODAY=$(date +'%Y-%m-%d')
          YESTERDAY=$(date -d '1 day ago' +'%Y-%m-%d')
          DAY_BEFORE_YESTERDAY=$(date -d '2 days ago' +'%Y-%m-%d')
          
          # Save current index.html with today's date
          cp index.html archive/${TODAY}.html
          
          # Remove files not matching the last three days
          for file in archive/*.html; do
            filename=$(basename "$file" .html)
            if [[ "$filename" != "$TODAY" && "$filename" != "$YESTERDAY" && "$filename" != "$DAY_BEFORE_YESTERDAY" ]]; then
              rm "$file"
            fi
          done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: .  # 确保包含根目录及其子目录（如archive）
